filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/inputlogs/*.log
    fields_under_root: true
    fields:
      log_type: ssh_simulated

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"
